# Generated by Django 5.0.6 on 2024-08-22 02:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du Type de Congé')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_leave_balance', models.PositiveIntegerField(default=0)),
                ('sick_leave_balance', models.PositiveIntegerField(default=0)),
                ('maternity_leave_balance', models.PositiveIntegerField(default=0)),
                ('exceptional_leave_balance', models.PositiveIntegerField(default=0)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(default=django.utils.timezone.now, verbose_name='Date de début')),
                ('date_fin', models.DateField(default=django.utils.timezone.now, verbose_name='Date de fin')),
                ('motif', models.TextField(default='Aucun motif fourni', verbose_name='Motif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVÉ', 'Approuvé'), ('REJETÉ', 'Rejeté')], default='EN_ATTENTE', max_length=10, verbose_name='Statut')),
                ('type_conge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conge.leavetype', verbose_name='Type de congé')),
            ],
        ),
    ]
