# Generated by Django 5.0.6 on 2024-08-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0003_alter_leaverequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='date_debut',
            field=models.DateField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='date_fin',
            field=models.DateField(verbose_name='Date de fin'),
        ),
    ]
