# Generated by Django 5.0.6 on 2024-08-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0005_leavebalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReligiousHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
