# Generated by Django 5.0.6 on 2024-08-25 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0007_employe_leaverequest_employe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='employe',
        ),
        migrations.DeleteModel(
            name='Employe',
        ),
    ]
