# Generated by Django 5.0.6 on 2024-08-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0008_remove_leaverequest_employe_delete_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='annual_leave_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='exceptional_leave_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='maternity_leave_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='sick_leave_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
