# Generated by Django 5.0.6 on 2024-08-27 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0010_leaverequest_holiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='holiday',
        ),
    ]
