# Generated by Django 5.0.6 on 2024-08-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0011_remove_leaverequest_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('content', models.TextField()),
            ],
        ),
    ]
