# Generated by Django 5.0.6 on 2024-08-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0012_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
